FROM nginx:stable-alpine
# RUN rm -rf /usr/share/nginx/html/*
COPY --from=dj:library /locallib/staticfiles /locallib/staticfiles
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# CMD ["nginx", "-g", "daemon off;"]