version: "3"

services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        environment: 
            - POSTGRES_PASSWORD=postgres
        volumes: 
            - library_data:/var/lib/postgresql/data
    dj:
        container_name: django
        build: .
        image: dj:library
        restart: always
        working_dir: /locallib
        command: uwsgi --ini uwsgi.ini
        volumes: 
            - media_data:/locallib/uploads
        depends_on:
            - db
        environment: 
            - DJANGO_SETTINGS=dev
    ng:
        container_name: nginx
        build: 
            context: .
            dockerfile: ./Dockerfile_ng
        restart: always
        ports: 
            - "80:80"
        volumes: 
            - media_data:/locallib/uploads
        depends_on: 
            - dj

volumes: 
    library_data:
    media_data:
        