version: "3"

services:
    db:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=postgres
        volumes: 
            - ./db_files:/var/lib/postgresql/data
    dj:
        container_name: dj
        build: .
        working_dir: /locallib
        command: python manage.py runserver 0.0.0.0:80
        ports: 
            - "80:80"
        depends_on:
            - db
        environment: 
            - DJANGO_SETTINGS=dev